#!/usr/bin/env python3
"""Regenerate the literature-collection inventory from metadata/papers.json.

Produces / refreshes (all derived from the single source of truth,
metadata/papers.json):

  * metadata/papers.json     -- fills sha256 for files that exist on disk
  * metadata/papers.csv      -- flat table (task schema)
  * metadata/papers.bib      -- one BibTeX entry per unique paper (verified
                                fields only; no fabricated DOI/venue)
  * metadata/checksums.sha256 -- `sha256  relative_path`, sha256sum -c compatible
  * metadata/download_status.md -- human-readable status report
  * README.md paper tables + counts, but ONLY between stable
    <!-- BEGIN:X -->/<!-- END:X --> markers, so hand-written prose is preserved.

Read-only w.r.t. the network and w.r.t. model code. Safe to re-run.

Usage:
    python scripts/generate_inventory.py
"""

from __future__ import annotations

import csv
import hashlib
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
METADATA = REPO / "metadata" / "papers.json"
CSV_PATH = REPO / "metadata" / "papers.csv"
BIB_PATH = REPO / "metadata" / "papers.bib"
SUMS_PATH = REPO / "metadata" / "checksums.sha256"
STATUS_PATH = REPO / "metadata" / "download_status.md"
README = REPO / "README.md"

COLUMNS = [
    "category", "system", "title", "authors", "year", "venue", "arxiv_id",
    "doi", "official_url", "pdf_url", "local_path", "sha256",
    "primary_or_supporting", "local_runnable_system", "download_status",
    "verification_status", "notes",
]

CATEGORY_ORDER = [
    "locally_runnable_systems", "core_foundations", "direct_extensions",
    "tracking_and_video", "segmentation_integrations",
    "deployment_and_efficiency", "domain_adaptations", "application_papers",
    "unverified_or_pending",
]

STOPWORDS = {"a", "an", "the", "of", "for", "and", "with", "to", "in", "on", "into", "via", "using"}


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for block in iter(lambda: fh.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def refresh_checksums(papers: list[dict]) -> None:
    for p in papers:
        local = p.get("local_path")
        if local and (REPO / local).exists():
            p["sha256"] = sha256_file(REPO / local)


def write_json(data: dict) -> None:
    METADATA.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def write_csv(papers: list[dict]) -> None:
    with CSV_PATH.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=COLUMNS)
        w.writeheader()
        for p in papers:
            w.writerow({c: p.get(c, "") for c in COLUMNS})


def bib_key(p: dict, used: dict[str, int]) -> str:
    first = (p.get("authors", "") or "").split(",")[0].strip()
    surname = re.sub(r"[^A-Za-z]", "", first.split()[-1]) if first else "anon"
    year = str(p.get("year", "") or "n")
    word = ""
    for w in re.findall(r"[A-Za-z0-9]+", p.get("title", "")):
        if w.lower() not in STOPWORDS:
            word = w.lower()
            break
    key = f"{surname.lower()}{year}{word}"
    if key in used:
        used[key] += 1
        key = f"{key}{chr(ord('a') + used[key] - 1)}"
    else:
        used[key] = 1
    return key


def bib_escape(s: str) -> str:
    return s.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")


def write_bib(papers: list[dict]) -> None:
    used: dict[str, int] = {}
    out: list[str] = [
        "% Generated by scripts/generate_inventory.py from metadata/papers.json.",
        "% One entry per unique paper. Only verified fields are emitted;",
        "% no DOI or venue is fabricated.\n",
    ]
    for p in papers:
        if p.get("verification_status", "").startswith("verified") is False:
            continue
        key = bib_key(p, used)
        venue = (p.get("venue") or "").lower()
        if p.get("arxiv_id") and (not p.get("venue") or "arxiv" in venue):
            etype, vfield = "misc", None
        elif any(w in venue for w in ("transactions", "journal")):
            etype, vfield = "article", "journal"
        else:
            etype, vfield = "inproceedings", "booktitle"
        fields = [
            f"  title = {{{bib_escape(p['title'])}}}",
            f"  author = {{{bib_escape(p.get('authors',''))}}}",
        ]
        if p.get("year"):
            fields.append(f"  year = {{{p['year']}}}")
        if vfield and p.get("venue"):
            fields.append(f"  {vfield} = {{{bib_escape(p['venue'])}}}")
        if p.get("arxiv_id"):
            fields.append(f"  eprint = {{{p['arxiv_id']}}}")
            fields.append("  archivePrefix = {arXiv}")
        if p.get("doi"):
            fields.append(f"  doi = {{{p['doi']}}}")
        url = p.get("official_url") or p.get("pdf_url")
        if url:
            fields.append(f"  url = {{{url}}}")
        out.append(f"@{etype}{{{key},\n" + ",\n".join(fields) + "\n}\n")
    BIB_PATH.write_text("\n".join(out))


def write_checksums(papers: list[dict]) -> None:
    lines = []
    for p in papers:
        if p.get("local_path") and p.get("sha256") and (REPO / p["local_path"]).exists():
            lines.append(f"{p['sha256']}  {p['local_path']}")
    SUMS_PATH.write_text("\n".join(sorted(lines)) + ("\n" if lines else ""))


def counts_by_category(papers: list[dict]) -> dict[str, int]:
    c: dict[str, int] = {}
    for p in papers:
        c[p["category"]] = c.get(p["category"], 0) + 1
    return c


def write_status(papers: list[dict]) -> None:
    def has_pdf(p):
        return bool(p.get("local_path")) and (REPO / p["local_path"]).exists()

    present = [p for p in papers if p.get("download_status") == "present" and has_pdf(p)]
    downloaded = [p for p in papers if p.get("download_status") == "downloaded" and has_pdf(p)]
    pending = [p for p in papers if p.get("download_status") == "pending"]
    unavailable = [p for p in papers if p.get("download_status") == "unavailable"]
    failed = [p for p in papers if str(p.get("download_status", "")).startswith("failed")]
    no_pdf = [p for p in papers if not p.get("local_path")]

    L: list[str] = ["# Literature Collection — Download & Verification Status", ""]
    L.append("_Generated by `scripts/generate_inventory.py`. Do not edit by hand._")
    L.append("")
    L.append(f"- Total records: **{len(papers)}**")
    L.append(f"- PDFs present/valid on disk: **{len(present) + len(downloaded)}**")
    L.append(f"- Pending download: **{len(pending)}**")
    L.append(f"- Unavailable (no open-access PDF): **{len(unavailable)}**")
    L.append(f"- Failed: **{len(failed)}**")
    L.append("")

    def section(title, rows, show_sha=True):
        L.append(f"## {title}")
        if not rows:
            L.append("- (none)")
            L.append("")
            return
        for p in rows:
            sha = (p.get("sha256") or "")[:12]
            extra = f" — `{sha}...`" if show_sha and sha else ""
            path = p.get("local_path") or "(no local file)"
            L.append(f"- **{p['title']}** — `{path}`{extra}")
        L.append("")

    section("Already present (reused valid PDFs)", present)
    section("Successfully downloaded", downloaded)
    section("Pending / to download", pending, show_sha=False)
    section("Unavailable (verified metadata, no open-access PDF)", unavailable, show_sha=False)
    section("Failed downloads", failed, show_sha=False)
    section("Records without a PDF (metadata only)", no_pdf, show_sha=False)
    STATUS_PATH.write_text("\n".join(L))


def md_link(p: dict) -> str:
    url = p.get("official_url") or p.get("pdf_url") or ""
    return f"[{p.get('arxiv_id') or 'link'}]({url})" if url else "—"


def primary_table(papers: list[dict]) -> str:
    order = ["grounding_dino", "mm_grounding_dino", "grounded_sam", "grounded_sam_2", "pet_dino"]
    labels = {
        "grounding_dino": "01 Grounding DINO",
        "mm_grounding_dino": "02 MM-Grounding-DINO",
        "grounded_sam": "03 Grounded SAM",
        "grounded_sam_2": "04 Grounded SAM 2",
        "pet_dino": "05 PET-DINO",
    }
    prim = {p["system"]: p for p in papers if p.get("primary_or_supporting") == "primary"}
    rows = ["| System | Primary paper | Year | Venue | Source | Local PDF |",
            "|---|---|---|---|---|---|"]
    for sysid in order:
        label = labels[sysid]
        if sysid == "grounded_sam_2":
            rows.append(f"| {label} | _software integration — no standalone paper_ | — | — | "
                        "[repo](https://github.com/IDEA-Research/Grounded-SAM-2) | "
                        "`papers/locally_runnable_systems/04_grounded_sam_2/README.md` |")
            continue
        p = prim.get(sysid)
        if not p:
            rows.append(f"| {label} | _missing_ | — | — | — | — |")
            continue
        rows.append(f"| {label} | {p['title']} | {p['year']} | {p['venue']} | "
                    f"{md_link(p)} | `{p['local_path']}` |")
    return "\n".join(rows)


def supporting_table(papers: list[dict]) -> str:
    rows = ["| Paper | Year | Venue | Supports | Source | Local PDF |",
            "|---|---|---|---|---|---|"]
    for p in papers:
        if p.get("primary_or_supporting") != "supporting":
            continue
        rows.append(f"| {p['title']} | {p['year']} | {p['venue']} | "
                    f"{p.get('local_runnable_system') or '—'} | {md_link(p)} | `{p['local_path']}` |")
    return "\n".join(rows)


def counts_table(papers: list[dict]) -> str:
    c = counts_by_category(papers)
    rows = ["| Category | Papers |", "|---|---|"]
    for cat in CATEGORY_ORDER:
        if cat in c:
            rows.append(f"| {cat} | {c[cat]} |")
    rows.append(f"| **total** | **{len(papers)}** |")
    return "\n".join(rows)


def replace_marker(text: str, name: str, body: str) -> str:
    begin, end = f"<!-- BEGIN:{name} -->", f"<!-- END:{name} -->"
    pat = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.DOTALL)
    repl = f"{begin}\n{body}\n{end}"
    return pat.sub(repl, text) if begin in text else text


def update_readme(papers: list[dict]) -> None:
    if not README.exists():
        return
    text = README.read_text()
    text = replace_marker(text, "PRIMARY_TABLE", primary_table(papers))
    text = replace_marker(text, "SUPPORTING_TABLE", supporting_table(papers))
    text = replace_marker(text, "CATEGORY_COUNTS", counts_table(papers))
    README.write_text(text)


def main() -> int:
    data = json.loads(METADATA.read_text())
    papers = data["papers"]
    refresh_checksums(papers)
    write_json(data)
    write_csv(papers)
    write_bib(papers)
    write_checksums(papers)
    write_status(papers)
    update_readme(papers)

    c = counts_by_category(papers)
    print("regenerated inventory:")
    print(f"  papers.json / papers.csv / papers.bib / checksums.sha256 / download_status.md")
    for cat in CATEGORY_ORDER:
        if cat in c:
            print(f"  {cat:28s} {c[cat]}")
    print(f"  {'total':28s} {len(papers)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
